<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0BR2GDR" failures="1" tests="1" name="Test" time="27.759" errors="0" timestamp="07 May 2019 19:55:20 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="27.403">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: passed expected [https://www.premierleague.com/?state=success] but found [https://users.premierleague.com/?redirect_uri=https://www.premierleague.com/&amp;amp;app=pl-web]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: passed expected [https://www.premierleague.com/?state=success] but found [https://users.premierleague.com/?redirect_uri=https://www.premierleague.com/&app=pl-web]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: passed expected [https://www.premierleague.com/?state=success] but found [https://users.premierleague.com/?redirect_uri=https://www.premierleague.com/&app=pl-web]
at com.stepsDef.StepDef.user_click_submit_button_and_appear_user_account_page_with_validation(StepDef.java:59)
at âœ½.And user click submit button and appear user account page with validation(C:/Users/palsa/eclipse-workspaceNew/PleagueFinal/src/main/resources/League.feature:10)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test -->
