<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0BR2GDR" failures="1" tests="2" name="Test" time="29.99" errors="0" timestamp="6 May 2019 20:00:41 GMT">
  <testcase classname="com.test.Home" name="getBrowser" time="11.034">
    <failure type="java.lang.AssertionError" message="passed expected [https://www.premierleague.com/matchweek/3296/blog] but found [https://users.premierleague.com/?redirect_uri=https://www.premierleague.com/&amp;amp;app=pl-web]">
      <![CDATA[java.lang.AssertionError: passed expected [https://www.premierleague.com/matchweek/3296/blog] but found [https://users.premierleague.com/?redirect_uri=https://www.premierleague.com/&app=pl-web]
	at com.test.Home.getBrowser(Home.java:34)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- getBrowser -->
  <testcase classname="com.test.Home" name="getBrowser" time="18.136"/>
</testsuite> <!-- Test -->
